# Generated by Django 5.0.7 on 2024-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='designation',
            field=models.CharField(default='Software Developer', max_length=100),
        ),
    ]
