# Generated by Django 5.0.7 on 2024-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0002_salaryslip_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
