# Generated by Django 5.0.7 on 2024-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0003_alter_salaryslip_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='department',
            field=models.CharField(default='Java', max_length=100),
        ),
    ]
