# Generated by Django 5.0.7 on 2024-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0004_salaryslip_date_of_joining_salaryslip_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
