# Generated by Django 5.0.7 on 2024-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0005_alter_salaryslip_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='allowances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
