# Generated by Django 5.0.7 on 2024-09-08 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0006_salaryslip_allowances_salaryslip_basic_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_salary_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='salary_slip_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
