# Generated by Django 5.0.7 on 2024-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0008_alter_salaryslip_net_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
