# Generated by Django 5.0.7 on 2024-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0009_salaryslip_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
