# Generated by Django 5.0.7 on 2024-09-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_is_leave'),
        ('employee', '0002_employeedetails_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'created_date')},
        ),
    ]
