# Generated by Django 5.0.7 on 2024-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
