# Generated by Django 5.0.7 on 2024-09-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_employeedetails_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(default='Not Completed', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'verbose_name': 'Today`s Task',
                'verbose_name_plural': 'Today Tasks',
            },
        ),
    ]
