# Generated by Django 5.0.7 on 2024-07-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemanagement',
            name='approval_status',
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='emp_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails'),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='pending_work_of_employee',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
