# Generated by Django 5.0.7 on 2024-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0002_remove_leavemanagement_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='pending_work_of_employee',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='reason',
            field=models.TextField(default='None'),
        ),
    ]
