# Generated by Django 5.0.7 on 2024-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0003_alter_leavemanagement_pending_work_of_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='pending_work_of_employee',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='reason',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
