# Generated by Django 5.0.7 on 2024-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='Medium', max_length=6),
        ),
    ]
