# Generated by Django 5.0.7 on 2024-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
